IF
    OnCreation()
    !GlobalGT("DMWWRandomBoring","GLOBAL",0)
THEN
    RESPONSE #100
        IncrementGlobal("DMWWRandomBoring","GLOBAL",1)
        CreateCreature("REBAND01",[488.558],NE)
        CreateCreature("REBAND02",[500.454],NE)
        CreateCreature("REBAND03",[552.476],NE)
        CreateCreature("REBAND04",[427.548],NE)
        CreateCreature("REBAND05",[525.591],NE)
        Continue()
END